#!/bin/sh

pg_url="http://ftp.postgresql.org/pub/source/v${PG_VERSION}/postgresql-${PG_VERSION}.tar.bz2"
wget $pg_url
tar xjvf postgresql-${PG_VERSION}.tar.bz2

cd postgresql-${PG_VERSION}

install_dir=/tmp/pg/postgresql-${PG_VERSION}
mkdir -p $install_dir

LDFLAGS='-Wl,--as-needed -Wl,-z,now' \
  CFLAGS='-fPIC -DLINUX_OOM_ADJ=0' \
  ./configure --prefix=$install_dir \
  --enable-integer-datetimes \
  --enable-thread-safety \
  --enable-debug \
  --disable-rpath \
  --with-gnu-ld \
  --with-pgport=5432 \
  --with-system-tzdata=/usr/share/zoneinfo \
  --without-tcl \
  --without-perl \
  --without-python \
  --with-krb5 \
  --with-gssapi \
  --with-libxml \
  --with-libxslt \
  --with-openssl
make && make install

cd $install_dir
echo $PG_VERSION > VERSION
